# Generated by Django 5.1.6 on 2025-02-25 06:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='projects'),
            preserve_default=False,
        ),
    ]
