# Generated by Django 5.1.6 on 2025-02-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
