# Generated by Django 5.1.6 on 2025-02-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrKzwI1LUg0ORMtSvgvjRjgHdTzAIu_rf2g&s', upload_to='', verbose_name='projects'),
        ),
    ]
