# Generated by Django 5.1.6 on 2025-02-25 12:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrKzwI1LUg0ORMtSvgvjRjgHdTzAIu_rf2g&s', max_length=255, verbose_name='projects'),
        ),
    ]
