# Generated by Django 5.1.6 on 2025-02-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_portfolioitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
