# Generated by Django 5.1.6 on 2025-02-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolioitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image',
        ),
    ]
