# Generated by Django 5.1.6 on 2025-02-25 07:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_portfolioitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqrKzwI1LUg0ORMtSvgvjRjgHdTzAIu_rf2g&s', max_length=255, verbose_name='portfolio'),
        ),
    ]
