# Generated by Django 5.1.6 on 2025-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Portfolio'),
        ),
    ]
