# Generated by Django 5.1.6 on 2025-02-25 12:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Portfolio'),
        ),
    ]
